### ISSUE TITLE
Spike: Unregister runtime artifacts

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-next#2619]
## Description / Steps to reproduce / Feature proposal
Spike for #2485 

Investigate on how to unbind/unregister LB artifacts:
- Model class
- Repository class
- Service proxy class
- Controller class
- DataSource class

Questions: 
1. Does this spike include all the LB artifacts? Or if we figure out a smaller subset, it's trivial for the rest?
2. Does the scope of the spike include the cache management mentioned by @jannyHou in [this comment](https://github.com/strongloop/loopback-next/issues/2485#issuecomment-473019623)?

**Comment by raymondfeng** [comment]
We now have the infrastructure in place, such as `ContextView`, `@inject.view`, and `@inject.getter`. The key is to extract certain logic into extension points and utilize the dynamic access to registered extensions. For example, the `RestServer` should be able to react on controller come and go.

**Comment by raymondfeng** [comment]
We also need to find out which artifacts may have impacts when they are changed. It also has something to do with binding scopes.

**Comment by bajtos** [comment]
> Does the scope of the spike include the cache management mentioned by @jannyHou in this comment?

Yes. Removing a controller must remove the REST API endpoints too.

> Does this spike include all the LB artifacts? Or if we figure out a smaller subset, it's trivial for the rest?

I think different artifacts may need different approach. For example, there may be very little work needed to unregister a model class. On the other hand, removing a controller is more involved, as we have to update the routing table.

It may be better to split this spike into smaller tasks, for example:
1. Controller class
2. Repository and Service proxy
3. Model class
4. DataSource class

I think we need to take into account dependencies between artifacts too. For example, it does not make sense to unregister a Repository class when there are controllers still using it. 

In the first iteration, I am fine to leave it up to developers to ensure they unregister all artifact types. We can investigate more robust solutions later.

The key requirements for the first iteration:
- When a controller + repo + model is unregistered, there must be no memory references remaining, so that V8 can release and collect the memory. Test case: write a loop creating & unregistering model+repo+controller. The process should use relatively constant memory, the memory usage must not grow.
- Similarly for controller + service proxy.
- Similarly for data-sources.
