### ISSUE TITLE
Spike: juggler-next in lb-next repo or new monorepo

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-next#3126]
## Description / Steps to reproduce / Feature proposal
Per discussion with @raymondfeng @bajtos:
If we're going to create juggler-next, should we:
- create a new monorepo for juggler and connectors
- put them all in loopback-next repo

Things to consider:
- How does each option affect the build pipeline?
- If we put everything in loopback-next repo, would it be an issue that our PRs will get out of date very easily and already a pain to keep rebasing it?

What was discussed but could be out of scope of this spike: 
- use of AzurePipelines

Related: https://github.com/strongloop/loopback-next/issues/890

**Comment by bajtos** [comment]
IMO, it's important to keep `@loopback/repository` in the same monorepo as the connectors, so that we can make changes across different modules.

At the same time, we may want to keep `@loopback/repository` in the same monorepo as the REST layer, because we are offering relatively tight integration between those two in the form of helpers generating OpenAPI spec describing Models. 

On the second thought, it should be possible to find a clear boundary between the REST layer and OpenAPI spec helpers, so that we can the implementation of OpenAPI helpers to the new Repository monorepo too. This will ensure that our abstractions are defined in such way that our default Repository ecosystem can be easily replaced by other ORMs like TypeORM.

**Comment by bajtos** [comment]
> On the second thought, it should be possible to find a clear boundary between the REST layer and OpenAPI spec helpers, so that we can the implementation of OpenAPI helpers to the new Repository monorepo too. This will ensure that our abstractions are defined in such way that our default Repository ecosystem can be easily replaced by other ORMs like TypeORM.

I started to look into ways how to reduce coupling between `@loopback/repository` and `@loopback/core` & `@loopback/context`. Most of the code depends on `@loopback/metadata` only, which is IMO fine, even if `@loopback/metadata` will live in a different monorepo than our `@loopback/repository`.

The code can be found here: https://github.com/strongloop/loopback-next/tree/chore/simplify-repository-imports

Unfortunately, there are few problematic places that I am not able to change in backwards-compatible way:

- Relation repositories are using `Getter` type. We can re-define the function in `@loopback/repository`, but that can create confusion -`Getter` imported from `@loopback/context` (or core) provides `Getter.fromValue` helper, but `Getter` imported from `@loobpack/repository` does not. Should we introduce a new package to provide `Getter` type & `Getter.fromValue` helper, possibly with other commonly used TypeScript types?
- The `@repository()` decorator relies on `Context`, `Injection` and `inject`, I think it would be too difficult (if possible at all) to change that. Perhaps it's a sign that we should have two packages - one for Model and Repository functionality that's not coupled with our DI/IoC framework, the other providing helpers binding ORM with our DI. If we take this approach, then perhaps we can move almost everything from `@loopback/repository` to a new package (e.g. `@loopback/orm`) that can live in the new monorepo, and then rework `@loopback/repository` to be a thin wrapper around that new package, adding stuff specific to our DI.

@raymondfeng thoughts?
