### ISSUE TITLE
Using hasMany relation and cascading ORM level in loopback4

### ISSUE THREAD

**Issue by sunilsmith** [loopbackio/loopback-next#3526]
I have created 2 models Author and Books where Author has hasMany relation with Book and Book has belongsTo relation with author.
While saving data using ORM models the cascading is not happening i.e

```json
{
    "authorId": 1,
    "name": "qwery",
    "experience": 2,
    "books": [{
        "BookId": 12,
        "category": "string"
    }]
}
```

The above should create a Author record in Author table and create a Book record with the authorId in Book table, which is not happening whereas from belongsTo it can able to create an Author record with just authorId.
can find the code in the following [GIT](https://github.com/Ambay54/loopback_postgres.git)

**Comment by dhmlau** [comment]
Transferred to `loopback-next` repo because this is about LB4. 
@sunilsmith, cross-posting my response to your [stackoverflow post](https://stackoverflow.com/questions/57391303/using-hasmany-relation-and-cascading-orm-level-in-loopback4): 

-----
You need to create a AuthorBookController to connect the two. Please see example code in here: https://github.com/strongloop/loopback-next/blob/master/examples/todo-list/src/controllers/todo-list-todo.controller.ts

**Comment by sestienne** [comment]
Hi, 

Why not in author controller just call in `deleteById` function : 
`this.authorRepository.books(id).delete();` ?

The function deleteById of a repository is able to take Options, the reference api doesn't describe them. What are them ? Not possible to give a cascade option ?
`(method) DefaultCrudRepository<Category, number | undefined, CategoryRelations>.deleteById(id: number | undefined, options?: AnyObject | undefined): Promise<void>`
Thanks a lot!

**Comment by bajtos** [comment]
> While saving data using ORM models the cascading is not happening

LoopBack does not support cascading operations (create, update, delete).
