### ISSUE TITLE
Add new user email verification tutorial

### ISSUE THREAD

**Issue by achrinza** [loopbackio/loopback-next#4872]
Loosely-related: #1979

Currently, there is no documentation on how to setup email verification for user sign-ups.

## Suggestion

As LoopBack 4 has an authorization mechanism, some users may need to extend it to support email verification.

## Use Cases

This addition will provide more guidance to new users of LoopBack 4 on how to write production-ready APIs.

## Examples

TBD

## Acceptance criteria

TBD - will be filled by the team.

**Comment by achrinza** [comment]
Duplicate of #1979

**Comment by dhmlau** [comment]
@achrinza, are we looking for something like https://loopback.io/doc/en/lb3/Registering-users.html in LB3?

**Comment by achrinza** [comment]
@dhmlau I believe so, this issue was spun off from https://github.com/strongloop/loopback-next/pull/4861#issuecomment-598149191

**Comment by dougal83** [comment]
Also... might want to purge http://www.embeddedjs.com/ links from the site too... nice gambling site now! 😆

**Comment by dhmlau** [comment]
Thanks @achrinza for submitting a PR to update the link! ❤️

**Comment by chrisLovesCode** [comment]
@achrinza 
Hey there,
so if i understand you guys right, https://loopback.io/doc/en/lb3/Registering-users.html will not work for LB**4** ?

i am currently interested in using loopback and i am a littlebit frustrated that the given user registration examples are not real world ready without email verification, since i was looking for a framework which has all the common user management stuff setup :(

everytime i google loopback email verification and such i always hit lb3 resources..

**Comment by achrinza** [comment]
@chrisLovesCode Sorry for the late reply; I believe you're looking for a built-in email verification system, while this issue is meant for a tutorial on custom email verification implementations.
