### ISSUE TITLE
"Content-Type" header is overwritten

### ISSUE THREAD

**Issue by agnes512** [loopbackio/loopback-next#5168]
@SephReed commented on [Mon Apr 20 2020](https://github.com/strongloop/loopback/issues/4321)

## Steps to reproduce
```
export class TestController {
  @get('/hello-page', {
    description: "Static page",
    responses: {}
  })
  async getHelloPage(
    @inject(RestBindings.Http.RESPONSE) res: Response,
  ) {
    res.setHeader("Content-Type", "text/html; charset=UTF-8");
    res.setHeader("Content-Type-Test", "text/html; charset=UTF-8");
    return `<html>Hello World</html>`;
  }
}
```

## Current Behavior
Content type is `text/plain`
<img width="344" alt="Screen Shot 2020-04-20 at 2 59 27 PM" src="https://user-images.githubusercontent.com/14002040/79794246-8f4e9600-8317-11ea-8bed-324bf93ca1e7.png">

A Content-Type-Test header was also set, it is the correct `text/html; charset=UTF-8`

## Expected Behavior

Content-Type should be `text/html; charset=UTF-8`

**Comment by jannyHou** [comment]
@agnes512 it's probably caused by the default content type set in the `write` action:
https://github.com/strongloop/loopback-next/blob/a81ce7e1193f7408d30d984d0c3ddcec74f7c316/packages/rest/src/writer.ts#L58

It happens after the controller function invoke, see https://github.com/strongloop/loopback-next/blob/a81ce7e1193f7408d30d984d0c3ddcec74f7c316/packages/rest/src/sequence.ts#L100-L103

**Comment by bajtos** [comment]
I think the current behavior is intentional. If the user wants to manipulate the response directly via `@inject(RestBindings.Http.RESPONSE)` then they should also send the response body using `res.send`.

For longer term, we should allow controller methods to return an object describing response status code and headers in addition to response body. See https://github.com/strongloop/loopback-next/issues/436

**Comment by SephReed** [comment]
Hmmm... okay.  I've thought of modifying my `sequence.ts` to catch these cases and handle `response.send()` on it's own.

The issue is that circumnavigating `response.send()` seems like it's going to create issues down the line.  I'm not sure what that function does, but assume it exists for a reason.

```
export class MySequence implements SequenceHandler {

  async handle(context: RequestContext) {
    const { request, response } = context;
    // do stuff
    const result = await magic();
    const headerHasContentType = magic();
    if (headerHasContentType) {
      request.send(result);
    } else {
       this.send(response, result); 
    }
}
```
