### ISSUE TITLE
using regexp in where filter on an property not defined in the model (additional prop) fails

### ISSUE THREAD

**Issue by rhiwn** [loopbackio/loopback-next#5741]
## Steps to reproduce

additional properties not defined in a model can't be searched for using a regexp filter
for example, this filter {"where":{"and":[{"c_range": {"regexp" : "/etern/i"}}]}} does not work when c_range is an additional property added to the data but not defined in the model. However, the same filter done on a property which is defined in the model works fine.

## Current Behavior

above filter applied to data that has additional properties in the data (not defined in the model) return an empty result. 
[]

## Expected Behavior

Expected to see all documents with that property matching the regexp filter.

## Additional information

using mongodb data source.

### Description

See https://github.com/strongloop/loopback-next/issues/5741#issuecomment-646779015

### Acceptance Criteria

- [ ] Query with regex filter on properties not defined in model should work.

**Comment by jannyHou** [comment]
confirmed with todo example. Using the memory db has the same result.

- Insert a new instance to db.json file
  ```
  "5": "{\"title\":\"loopback\",\"desc\":\"Every.Last.One.\",\"id\":5,\"random\":\"loopback\"}"
  ```
- Filter `{"where": {"title": {"regexp" : "/k/"}}}`  returns the 5th item.
- Filter `{"where": {"random": {"regexp" : "/k/"}}}` returns `[]`

**Comment by mrmodise** [comment]
Am interested in looking at this. Thanks

**Comment by mrmodise** [comment]
> confirmed with todo example. Using the memory db has the same result.
> 
> * Insert a new instance to db.json file
>   ```
>   "5": "{\"title\":\"loopback\",\"desc\":\"Every.Last.One.\",\"id\":5,\"random\":\"loopback\"}"
>   ```
> * ✔️ Filter `{"where": {"title": {"regexp" : "/k/"}}}`  returns the 5th item. (regex filter for property in model)
> * ✔️ Filter `{"where": {"random": "loopback"}}` returns the 5th item. (eq filter for property not in model)
> * 🚫 Filter `{"where": {"random": {"regexp" : "/k/"}}}` returns `[]` (regex filter for property not in model)

After spending a bit of time on this I was able to find where the issue is but am still not sure how to go about resolving it. 

1. If you change the Filter to: `{"where": {"random": {"regexp" : "k"}}}` return 5th item
2. If you maintain `{"where": {"random": {"regexp" : "/k/"}}}` returns `[]`. What I observed here is that in the `legacy-juggler-bridge.ts` the find method behaves different if you filter based on existing properties vs additional properties.

**Existing properties**
For existing properties, the find method correctly formats the regexp in the filter meaning this `{"where": {"title": {"regexp" : "/k/"}}}` changes to `{ where: { **title**: { regexp: **/k/** } } }` notice the regexp value. However, if you use additional properties it results in `{ where: { random: { regexp: **'/k/'** } } }` meaning the regexp is not respected here thus omitted. However, if you hard-code the filter it returns expected result. See below:

`async find(
    filter?: Filter<T>,
    options?: Options,
  ): Promise<(T & Relations)[]> {
    const include = filter?.include;
    // hard code filter
    filter = { where: { random: { regexp: /k/ } } }; // this will return 5th item
    const models = await ensurePromise(
      this.modelClass.find(this.normalizeFilter(filter), options),
    );
    const entities = this.toEntities(models);
    return this.includeRelatedModels(entities, include, options);
  }`

I am new to Loopback 4 so am still exploring how best to solve this problem so assistance is highly welcomed and appreciated @bajtos @raymondfeng @jannyHou

**Comment by bajtos** [comment]
Here is the code in juggler that's normalizing/coercing filter values to convert regular expressions from strings to `RegExp` instances:

https://github.com/strongloop/loopback-datasource-juggler/blob/2f867576b66fe535aa1f82bceaaa680ecd4eec6c/lib/model-utils.js#L382-L496

Notice that we are skipping the coercion if the property is not defined in the model:

https://github.com/strongloop/loopback-datasource-juggler/blob/2f867576b66fe535aa1f82bceaaa680ecd4eec6c/lib/model-utils.js#L403-L405

A possible solution is to apply RegExp coercion for all properties, even if they are not defined in the model. Personally, I think we should make this change to all operator-based coercion rules (`inq`, `like`, etc.). As I see it, we have two kinds of coercion rules:
- The first kind relies on the property type as defined in the model - e.g. we want to convert string `'false'` to boolean value `false`. These rules cannot be applied to free-form properties, because we don't know what's the expected type.
- The second kind depends on the operator used  - e.g. `inq` expects an array, `regexp` a regular expression. These rules are independent of property definitions and therefore can be applied to free-form properties too.

So essentially we want to move the following code block before the check if a property is defined.

https://github.com/strongloop/loopback-datasource-juggler/blob/2f867576b66fe535aa1f82bceaaa680ecd4eec6c/lib/model-utils.js#L443-L496

It's important to include a good test coverage to avoid regressions, see [test/basic-querying.test.js](https://github.com/strongloop/loopback-datasource-juggler/blob/2f867576b66fe535aa1f82bceaaa680ecd4eec6c/test/basic-querying.test.js) for the existing test suite.

**Comment by mrmodise** [comment]
Thanks @bajtos will get right to it. This definitely helped a lot

**Comment by mrmodise** [comment]
> - > The second kind depends on the operator used - e.g. inq expects an array, regexp a regular expression. These rules are independent of property definitions and therefore can be applied to free-form properties too.

@bajtos managed to resolve the issue but am not feeling confident about whether this check: https://github.com/strongloop/loopback-datasource-juggler/blob/82ecf451c5ae8d4dcb32e2e5f1a16ec2060d74b6/lib/model-utils.js#L465 address your point above

**Comment by mrmodise** [comment]
@raymondfeng @bajtos am stuck on the testing of this logic. Looking at the `model-utils.test.js` it looks like its mostly testing the coercing of data types but in this case we want to test the whether if i pass a where clause with regexp filter that it will be returned, as part of where clause? this is similar to most tests in `loopback-dl.test.js` thus a bit of confusion on my end where these should live

**Comment by mrmodise** [comment]
@bajtos @raymondfeng PR ready for review. Unfortunately, some pipelines are failing and I don't think they're related to my changes
