### ISSUE TITLE
Juggler stores null objects as string "null" instead of value null in relational datasources

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [loopbackio/loopback-next#5764]
Note: this is actually a bug in strongloop/loopback-datasource-juggler, but the issue template there specifically instructs to report the issue here when working with LB4, so ...

## Steps to reproduce

* Create an entity type with an Object property
* Map this to a JSON/JSONB column in PostgreSQL
  * This bug is visible if you map it to a textual column in any other DB too I think
* Make the property & column accept `NULL` values
* Try to save a instance with this property as `null`

## Current Behavior

Juggler sees it is an object column and unconditionally uses `JSON.stringify` to prepare the value for the database: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L183

## Expected Behavior

`null` in JS/TS land should become `NULL` in the database, not a not-null value containing the string or JSON value `null`.

Put another way, if you save `null`, it should show up when you do a `select ... where column is null`.

## Link to reproduction sandbox

https://github.com/strongloop/loopback-next/compare/master...mgabeler-lee-6rs:issue/5764

Added a failing test demonstrating the problem to the `todo` example. Had to make the Memory datasource pretend to be relational to reproduce the issue I see with PostgreSQL, as the problem logic in the juggler only fires for relational datastores.

## Additional information

* node version info: `linux x64 10.17.0`
* dependency info: using `rush` so suggested command doesn't work, but ...
  * `"@loopback/repository": "2.4.0"`
  * `loopback-datasource-juggler: 4.21.2`

## Related Issues

Haven't found any yet

**Comment by bajtos** [comment]
Thank you for a detailed bug report, @mgabeler-lee-6rs 

I agree with you that storing `null` as a string `'null'` is not optimal.

It makes me wonder though, do we want to distinguish between `null` and `undefined` values? I think the current implementation is mapping `undefined` to SQL value `NULL`. Are we ok to map `null` to `NULL` too? If we implement such mapping, then I think `null` values won't be preserved - LoopBack will return `undefined` when the value is read back from the database.

```ts
const created = await productRepo.create({rating: null});
// stores `rating` with SQL `NULL` value
const found = await productRepo.findById(created.id);
// `found.rating` is `undefined`
```

Maybe the current implementation is intentional? When I think about storing JSON objects:

- An object value `{"foo": "bar"}` is stored as `SET data='{"foo": "bar"}'`
- A null value is stored as `SET data='null'`

Let's discuss!

@zbarbuto I found your PR https://github.com/strongloop/loopback-connector-postgresql/pull/304 that added basic JSON support to our postgresql connector. Do you have any opinions on how should we handle `null` values?

**Comment by mgabeler-lee-6rs** [comment]
For non object properties, nulls are stored as SQL NULL. Object properties
stored as JSON should be consistent with this.

Also, SQL NULL values are returned as null, not undefined as you suggest,
at least with the PostgreSQL connector.

Also also, storing SQL NULL is far more idiomatic, and more efficient (e.g.
PostgreSQL just keeps a bitmap of the null/not-null columns in a row, so
storing NULL takes zero bytes), not to mention interoperable.

**Comment by mgabeler-lee-6rs** [comment]
I should also call out the test case in the sample repo, storing nulls as
the string know prevents actually being able to locate those records with
queries, not to mention making it impossible to write good database
constraints, for example checking if a column is no based on the value of
another column

**Comment by mgabeler-lee-6rs** [comment]
Any followup thoughts on this? I contend that this result of the current behavior is a severe anti-pattern/bug:
* `repo.create({jsonProperty: null})` ⇒ entity
* `repo.find({where: {jsonProperty: null}})` ⇒ does not include entity
