### ISSUE TITLE
with mongodb legacy-juggler findById returns unwanted id field in embedded documents

### ISSUE THREAD

**Issue by Fr4nZ82** [loopbackio/loopback-next#6029]
> **Note:** This issue has been posted elsewhere:
> - https://stackoverflow.com/q/63172557

Steps to reproduce

```//the model
export class NestedDoc extends Model{
  @property() myProp1?: string;
  @property() myProp2?: number;
}

export class MyEntity extends Entity {
  @property({
    type: 'string',
    id: true,
  })
  id: string;

  @property({
    type: 'string',
    required: true,
  })
  name: string;

  @property() nested?: NestedDoc;`

//in the controller
await this.MyEntityRepository.findById(myEntity.id);
```

## Current Behavior

the result object is
`
 {
  "_id": {
    "$oid": "5f228e05ae69644ed8f31445"
  },
  "name": "entityname",
  "nested": {
    "id": null,
    "myProp1": "prop1",
    "myProp2": 2
  }
}
`

## Expected Behavior

do not return non-existent "id" fields in nested objects

win32 x64 13.10.1
+-- @loopback/authorization@0.6.2
+-- @loopback/boot@2.3.5
+-- @loopback/context@3.9.2
+-- @loopback/core@2.9.1
+-- @loopback/express@1.2.5
+-- @loopback/http-server@2.1.9
+-- @loopback/openapi-v3@3.4.5
+-- @loopback/repository@2.9.0
+-- @loopback/security@0.2.14
+-- @loopback/service-proxy@2.3.4
+-- loopback-connector-mongodb@5.2.2

**Comment by Fr4nZ82** [comment]
After many test i see that the issue is only on the findById that returns that non-existent id fields. The corrupt data was then saved to db in other parts of the code that I had not seen

**Comment by Fr4nZ82** [comment]
any news? also findOne has the same issue... my workaroud is
```
export const stripNullId = <T>(_obj: T): T => {
  const obj = _obj as any;
  //console.log('OBJ:', obj)
  if (Array.isArray(obj)) {
    obj.forEach((o: any) => {
      stripNullId(o);
    });
  } else {
    if (obj === null) return obj
    Object.keys(obj).forEach((key) => {
      if (
        key == 'id' &&
        (obj[key] == null ||
          obj[key] == undefined ||
          (obj[key] != 0 && !obj[key]))
      ) {
        return delete obj[key];
      } else if (
        ![
          'string',
          'number',
          'boolean',
          'bigint',
          'function',
          'symbol',
          'undefined',
        ].includes(typeof obj[key]) &&
        obj[key] != null &&
        !!obj[key]
      ) {
        return stripNullId(obj[key]);
      } else return;
    });
  }
  return obj as T;
};
export class CustomCrudRepository<
  T extends Entity,
  ID,
  Relations extends object = {}
  > extends DefaultCrudRepository<T, ID, Relations> {
  async findById(
    id: ID,
    filter?: FilterExcludingWhere<T>,
    options?: AnyObject,
  ): Promise<T & Relations> {
    const res = await super.findById(id, filter, options);
    return stripNullId(res);
  }
  async findOne(
    filter?: Filter<T>, options?: Options
  ): Promise<(T & Relations) | null> {
    const res = await super.findOne(filter, options);
    return stripNullId(res);
  }
}
```
but stripNullId is slow for big object (like [animationData ](https://raw.githubusercontent.com/airbnb/lottie-web/master/demo/bodymovin/data.json)of Lottie-web player)

**Comment by Fr4nZ82** [comment]
i just found that the problem also extends to optional properties. For example, if I have
```
@model()
export class LockedElement extends Model {
  @property({type: 'string'}) name: string
  @property({type: 'string'}) qrText?: string

  constructor(data?: Partial<LockedElement>) {
    super(data);
  }
}
```
and insert the object 
```
new LockedElement({
  name: 'anystring'
})
```
when I do any type of "find", the result is
```
{
  name: 'anystring',
  qrText: undefined
}
```
that it would not be a big problem except for the fact that when I get back from the client the open api validator gives me an error not being string value but null

**Comment by jannyHou** [comment]
Same issue as https://github.com/strongloop/loopback-next/issues/6800
And copy a possible solution here:

The problem is https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model.js#L88
When the retrieved customer’s address property gets converted to an instance of Address , that line has an additional id field even it’s not defined in the Address model.

Quoted solution from Miroslav:

Actually, I think the code building the juggler model is correct:
https://github.com/strongloop/loopback-next/blob/ec4c10c1d38ba80f59014ef447565894cf8b484b/packages/repository/src/repositories/legacy-juggler-bridge.ts#L176-L210
The problem is that we are attaching the embedded model to the datasource, which in turn adds a PK (id property) to the model definition:
https://github.com/strongloop/loopback-next/blob/ec4c10c1d38ba80f59014ef447565894cf8b484b/packages/repository/src/repositories/legacy-juggler-bridge.ts#L211

I think the behavior should be as follows:
- If the juggler model is backing the LB4 model the repository is for, then we must keep calling modelClass.attachTo(dataSource)
- If the juggler model is created for nested/embedded models, then we must attach it to the dataSource.
A possible implementation is to introduce options: {attachToDataSource: boolean} argument to ensurePersistedModel and definePersistedModel functions and then use the new option to decide whether a model should or should not be attached. I think we should be attaching by default for backwards compatibility, and change resolvePropertyType to set attachToDataSource: false.

**Comment by MiddleMan5** [comment]
Still relevant

**Comment by MiddleMan5** [comment]
This is still an issue, @jannyHou can you reopen?

**Comment by rodonal** [comment]
This problem persists as of August 2024.
