### ISSUE TITLE
passport-login example fails when using mongodb

### ISSUE THREAD

**Issue by argupta23** [loopbackio/loopback-next#6217]
## Steps to reproduce
Install Mongodb connector and create a datasource for mongodb.
Replace all instances of db(memory) with mongodb

The one thing that I did not do was to update "index.ts" within  "src" folder that still refers to "Db/memory". 

`
  lbApp.bind('datasources.config.db').to({
    name: 'db',
    connector: 'memory',
    localStorage: '',
    file: dbBackupFile ? path.resolve(__dirname, dbBackupFile) : undefined,
  });
`
It is not clear to me what changes need to be made here. Guidance is appreciated.

## Current Behavior
When using Google Oauth2 authentication after the user is rightfully authenticated the browser displays the below error

Error
404 Entity not found: User with id null
code: ENTITY_NOT_FOUND

When using db(memory) the same user is authenticated successfully and one can I can see his details.

Turning on tracing at the loopback:connector:mongodb* level it looks like monogdb is reporting 

     loopback:connector:mongodb all User { where: { id: NaN }, limit: 1, offset: 0, skip: 0 } null [] +4ms

Within mongodb I see two schema's associated with the user.

User contains

  _id:5f49587538dd7fc09a00c710   <-- this is mongodb generated
   name:"anil gupta"
   username:"argupta@xxxx.com"
   email:"argupta@xxxxx.com"

UserIdentity contains

   _id:"102xxxxxxxxxxxxxxxx574"  <--- this is google ID edited 
   provider:"google"
   profile:Object
   emails:Array
      0:Object
         value:"argupta@xxxxx.com"
         type:"account"
   authScheme:"google"
   created:2020-08-28 20:51:20.515
   userId:5

Switching from Db(memory) to real database should not impact software functionality.

## Additional information

a@backend:~/beta/test/loopback4-example-passport-login$   node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 12.18.2

a@backend:~/beta/test/loopback4-example-passport-login$ npm ls --prod --depth 0 | grep loopback
@loopback/example-passport-login@1.5.4 /home/argupta/beta/test/loopback4-example-passport-login
├── @loopback/authentication@6.0.0
├── @loopback/authentication-passport@2.1.12
├── @loopback/boot@2.5.0
├── @loopback/core@2.9.4
├── @loopback/mock-oauth2-provider@0.1.6
├── @loopback/repository@2.11.1
├── @loopback/rest@6.1.0
├── @loopback/rest-crud@0.8.12
├── @loopback/rest-explorer@2.2.9
├── @loopback/security@0.2.17
├── @loopback/service-proxy@2.3.7
├── loopback-connector-mongodb@5.3.0

There are few other observations related to this example that need to be fixed.
in "authentication-strategy-providers / google.ts" 
line 9 currently reads
     import {StrategyOption} from 'passport-facebook';
this should actually be
     import {StrategyOption} from 'passport-google-oauth2';

Acceptance Criteria:

Fix the following problems when using mongodb connector:

- [ ] login with google account errors in
        ```
         Error
         404 Entity not found: User with id null
         code: ENTITY_NOT_FOUND
        ```
- [ ] UserCredentials doesn't have userId correctly generated.

**Comment by argupta23** [comment]
@achrinza 

I tried to look into this a bit more today and here are some additional updates.

1. I put some console.log statements in user.service.ts  under async LinkExternal Profile and async CreateUser
2. When using DB(memory) the "userId" generated/assigned sequential for external accounts is 1,2,3 and so on
3. When using DB(mongodb) the "userId" generated/assigned for external accounts is either a 5 or NaN. I have tried this with 2 different accounts, same result.  

Within mongodb"UserIdentity" schema I have
Account 1
_id:"1026xxxxxxxxxxxxxxxxxxxxxx4"
provider:"google"
profile:Object
authScheme:"google"
created:2020-08-30 23:44:19.827
userId:5 or NaN

Account2
_id:"1003xxxxxxxxxxxxxxxxxxxxxx2"
provider:"google"
profile:Object
authScheme:"google"
created:2020-08-30 23:45:19.827
userId:5 or NaN



console.log after "let profile"
1--userid:1----- when using DB(memory) it is incremented properly.
1--userId:NaN or 5 ----- when using DB(mongodb) it is always 5 or NaN

An additional question 
for locally created accounts under "UserCredentials" schema what should the value for "userId" be? For me it always ends up with NaN (within mongodb). Is that right?

Within mongodb"UserCredentials" schema I have
_id:"b@b.com"
password:"Testxxxx!"
userId:NaN

I hope this helps in debugging the issue.

**Comment by dhmlau** [comment]
@argupta23, when you're changing the datasource from memory to mongodb, did you change the existing `.ts` file or create a new datasource? 
If you create a new datasource, make sure you've updated the repositories to point to the new one. e.g. https://github.com/strongloop/loopback-next/blob/master/examples/passport-login/src/repositories/user-credentials.repository.ts#L16. 

I'm not sure why the passport-login example is calling `lbApp.bind('datasources.config.db')` explicitly. But if it's needed, please make sure it's pointing to the mongodb datasource as well. 

Hope it helps.

**Comment by argupta23** [comment]
@dhmlau 
Yes, I am aware of the changes I need to make when changing datasources.

I have added loopback-connector-mongodb to the repo and then updated the datasources.ts/index.ts file with the following changes which I switch depending on how I want to test.

**src/datasoruces/db.datasource.ts**
const config = {
  name: 'db',
  // connector: 'mongodb',
  // url: 'mongodb://172.20.20.21:27017/backendbeta',
  // host: '',
  // port: 0,
  // user: '',
  // password: '',
  // database: '',
  // useNewUrlParser: true,
  connector: 'memory',
  localStorage: '',
  file: './data/db.json',
};

**within src/index.ts**
export async function setupApplication(
  lbApp: RestApplication,
  dbBackupFile?: string,
) {
  lbApp.bind('datasources.config.db').to({
    name: 'db',
    // connector: 'mongodb',
    // url: 'mongodb://172.20.20.21:27017/backendbeta',
    // host: '',
    // port: 0,
    // user: '',
    // password: '',
    // database: '',
    // useNewUrlParser: true,
    connector: 'memory',
    localStorage: '',
    file: dbBackupFile ? path.resolve(__dirname, dbBackupFile) : undefined,
  });

My updates from yesterday are based around this configuration. Please let me know if I am doing something wrong or if you need more info from my side.

Thanks

**Comment by dhmlau** [comment]
@jannyHou, could you please take a look? Thanks.

**Comment by jannyHou** [comment]
I reproduced the `userId: NaN` error with mongodb connector, but couldn't get the google login work.

I fixed:

```
There are few other observations related to this example that need to be fixed.
in "authentication-strategy-providers / google.ts"
line 9 currently reads
import {StrategyOption} from 'passport-facebook';
this should actually be
import {StrategyOption} from 'passport-google-oauth2';
```

and created `oauth2-providers.json`, set the ENV `OAUTH_PROVIDERS_LOCATION='../oauth2-providers.json'`

**But somehow my google login keeps directing to `passport-facebook`**:
```
Unhandled error in GET /auth/thirdparty/google: 500 TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/jannyhou/Desktop/September/loopback-next/examples/passport-login/node_modules/passport-oauth2/lib/strategy.js:86:34)
    at new Strategy (/Users/jannyhou/Desktop/September/loopback-next/examples/passport-login/node_modules/passport-facebook/lib/strategy.js:56:18)
    at new FacebookOauth (/Users/jannyhou/Desktop/September/loopback-next/examples/passport-login/dist/authentication-strategy-providers/facebook.js:17:25)
    at /Users/jannyhou/Desktop/September/loopback-next/packages/context/dist/resolver.js:48:16
    at Object.transformValueOrPromise (/Users/jannyhou/Desktop/September/loopback-next/packages/context/dist/value-promise.js:257:16)
```

Need more time to investigate. In case anyone happen to know the reason?

**Comment by jannyHou** [comment]
@argupta23 

> Related to the NAN issue, do you think it is related to the fact that the "user-credentials/user-identity" models don't have "generated: true" for the "id" field?

This is an easy update. The reason why switching to mongodb connector fails is, in this example, the User model has a number type id. While a mongodb objectId field doesn't accept number, it has to be a string.


Update as:

- change the `User` id from number to string:
  ```ts
  @property({
    type: 'string',
    id: true,
    generated: true,
  })
  id: string;
  ```
- add mongodb config in both `UserCredentials` and `UserIdentity` models:
  ```ts
  @belongsTo(() => User, {}, {mongodb: {dataType: 'ObjectID'}})
  userId: string;
  ```
- remove all `parseInt` through the example because id is already a string


The backend result:

```
{
	"_id" : "test3@fake.com",
	"password" : "12345abcde",
	"userId" : ObjectId("5f5a96d6ed1b44ce5cfbe120")
}
```

And back to your report in "Switching from Db(memory) to real database should not impact software functionality.", I think this assumption is too magic, for example, at least each connector requires its corresponding property configurations. The smooth db switching only applies when:

- the User id is string 
- the properties are well decorated with mongodb config

We can either document this instruction or update the example with my config above. I prefer to document it clearly, cuz people may need to consider using other dbs with different situations to deal with.

WDYT?

**Comment by jannyHou** [comment]
Ah, good news, the 3rd-party login is also solved!

Same as the configurations above, the key is to change the UserIdentity's belongsTo decorator with mongodb config specified. 

I can login with my google account successfully. And result of the stored identity:

```
db.UserIdentity.find().pretty()
{
	"_id" : "102771250582952923905",
	"provider" : "google",
	"profile" : {
		"emails" : [
			{
				"value" : "jannyhou2015@gmail.com",
				"type" : "account"
			}
		]
	},
	"authScheme" : "google",
	"created" : ISODate("2020-09-10T21:24:57.391Z"),
	"userId" : 5
}

```

**Comment by argupta23** [comment]
@jannyHou,

Your latest reply is exactly the problem I described 12 days ago in my update.

1. why is userId coming up as 5? IMO it should be a mongodb Object that is auto generated?

After having created this entry are you able to successfully login via the JADE webpage? I don't think you can. You will get an error.

Also try to add a second user account and I believe you will see that it still puts the userId as 5 for that user.

**Comment by jannyHou** [comment]
@argupta23 ok I didn't realize the userId is not correct. But I am able to login and that's why I thought the problem is solved, see:

<img width="994" alt="Screen Shot 2020-09-11 at 2 27 32 PM" src="https://user-images.githubusercontent.com/12554153/92960078-f261d600-f43a-11ea-89e1-a0ab4223c38d.png">

I will take another look of why the userId is 5.

**Comment by jannyHou** [comment]
BTW, thank you @argupta23 for discovering the bug of: 
```
There are few other observations related to this example that need to be fixed.
in "authentication-strategy-providers / google.ts"
line 9 currently reads
import {StrategyOption} from 'passport-facebook';
this should actually be
import {StrategyOption} from 'passport-google-oauth2';
```

would you like to submit a small PR and help us fix it?

**Comment by jannyHou** [comment]
@argupta23 The problem is here:

https://github.com/strongloop/loopback-next/blob/9892b35ff771e40b9b2c3a5c5d7e17104a863211/examples/passport-login/src/services/user.service.ts#L110

The userIdentity's `id` field is from `profile`'s `id`:

https://github.com/strongloop/loopback-next/blob/9892b35ff771e40b9b2c3a5c5d7e17104a863211/examples/passport-login/src/authentication-strategies/types.ts#L65

which is just a common string, not an ObjectId and cannot be converted into ObjectId. 

Again, this app is not designed to switch to other dbs, so it doesn't take it into consideration. To make it work with mongodb, we have to redesign to:

- treat the profile id as a common field of model `UserIdentity`
- modify the `UserIdentity.findById()` method to be sth. like `UserIdentity.findByProfileId()`

@argupta23 would that answer your question? I don't know whether we have the bandwidth to make that change, if you need it urgently, would you like to submit a PR fixing it?

And same for the small bug in https://github.com/strongloop/loopback-next/issues/6217#issuecomment-691250017 :) If you don't mind, it is just a few lines' change.
