### ISSUE TITLE
Change swagger with redoc

### ISSUE THREAD

**Issue by mdbetancourt** [loopbackio/loopback-next#6490]
## Suggestion
Use redoc to render documentation instead of swagger
## Use Cases
Redoc has so many features 
like code samples
![image](https://github.com/Redocly/redoc/raw/master/docs/images/code-samples-demo.gif)

interactive documentation for nested objects
![image](https://github.com/Redocly/redoc/raw/master/docs/images/nested-demo.gif)

support to discriminators & oneOf
![image](https://github.com/Redocly/redoc/raw/master/docs/images/discriminator-demo.gif)

Also autogenerate more samples than swagger

## Acceptance criteria

TBD - will be filled by the team.

**Comment by achrinza** [comment]
I've looked at redoc in the past, it does look pretty good.

Though I'd prefer if we introduce it as its own separate package (i.e `@loopback/redoc`) instead of replacing the existing API Explorer. Reason being the API Explorer is a lot simpler and may be better-suited for some projects.

Also since `@loopback/api-explorer` is already a "mature" package, replacing it may cause unnecessary friction from the community needing to adapt and adopt redoc. I'd much prefer leaving that alone since it's also relatively low-maintenance.
