### ISSUE TITLE
Error: EMFILE, Too many open files

### ISSUE THREAD

**Issue by bala-fashiondx** [loopbackio/loopback-next#6669]
Running a loopback application inside docker container . 

**The file descriptor was going on increasing  for datasource as mongodb (Checked using lsof | wc -l )**

_I need to implement garbage collection in lb4 .. Please suggest !!!_

**Comment by dhmlau** [comment]
@bala-fashiondx, I believe you're using LB4, so I just transferred this issue to the loopback-next repo. Please let me know if that's not the case.

**Comment by achrinza** [comment]
Hi @bala-fashiondx, apologies for the delayed reply; I've not been able to replicate the issue from my end. Would it be possible to follow through the [Bug report template](https://github.com/strongloop/loopback-next/issues/new?labels=bug&template=Bug_report.md) so that we can gather more information on the issue?
